// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizGame.Api.Data;

#nullable disable

namespace QuizGame.Api.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260205180402_SeedQuestions")]
    partial class SeedQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizGame.Api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Berlin", "Paris", "Rome", "Madrid" },
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "Earth", "Venus", "Mars", "Jupiter" },
                            Text = "Which planet is known as the Red Planet?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "3", "4", "5", "6" },
                            Text = "What is 2 + 2?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain" },
                            Text = "Who wrote Romeo and Juliet?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
