// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizGame.Api.Data;
using QuizGame.Api.Models;

#nullable disable

namespace QuizGame.Api.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260213164327_AddGameHistory")]
    partial class AddGameHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizGame.Api.Models.GameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<PlayerResult>>("PlayerResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("QuizGame.Api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectOptionIndex")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Berlin", "Paris", "Rome", "Madrid" },
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "Earth", "Venus", "Mars", "Jupiter" },
                            Text = "Which planet is known as the Red Planet?"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "3", "4", "5", "6" },
                            Text = "What is 2 + 2?"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain" },
                            Text = "Who wrote Romeo and Juliet?"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CorrectOptionIndex = 3,
                            Options = new List<string> { "Atlantic", "Indian", "Arctic", "Pacific" },
                            Text = "What is the largest ocean on Earth?"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "5", "6", "7", "8" },
                            Text = "How many continents are there?"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "25", "30", "35", "40" },
                            Text = "What is 15% of 200?"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "10", "11", "12", "14" },
                            Text = "What is the square root of 144?"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "54", "56", "58", "64" },
                            Text = "What is 7 × 8?"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "3.12", "3.14", "3.16", "3.18" },
                            Text = "What is the value of Pi rounded to two decimal places?"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Childs", "Children", "Childes", "Childern" },
                            Text = "What is the plural of 'child'?"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "Sad", "Angry", "Joyful", "Tired" },
                            Text = "Which word is a synonym for 'happy'?"
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            CorrectOptionIndex = 3,
                            Options = new List<string> { "Noun", "Verb", "Adjective", "Adverb" },
                            Text = "What type of word is 'quickly'?"
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Him went to the store.", "He went to the store.", "He goed to the store.", "Him goed to the store." },
                            Text = "Which sentence is grammatically correct?"
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "Runned", "Ran", "Runed", "Running" },
                            Text = "What is the past tense of 'run'?"
                        },
                        new
                        {
                            Id = 16,
                            Category = 3,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "The method runs on a separate thread", "The method contains asynchronous operations", "The method is static", "The method returns void" },
                            Text = "What does the 'async' keyword indicate in C#?"
                        },
                        new
                        {
                            Id = 17,
                            Category = 3,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "ILogger", "IServiceProvider", "IConfiguration", "IHostBuilder" },
                            Text = "Which interface is used for dependency injection in .NET?"
                        },
                        new
                        {
                            Id = 18,
                            Category = 3,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "3000", "8080", "5000", "4200" },
                            Text = "What is the default port for an ASP.NET Core application in development?"
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            CorrectOptionIndex = 1,
                            Options = new List<string> { "FirstOrDefault", "Single", "Find", "Where" },
                            Text = "Which LINQ method returns a single element or throws if none is found?"
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            CorrectOptionIndex = 2,
                            Options = new List<string> { "HttpContext", "DbContext", "ChangeTracker", "ModelBuilder" },
                            Text = "What does EF Core use to track changes to entities?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
